[build.environment]
# NODE_OPTIONS = "--max_old_space_size=4096"
NODE_VERSION = "22.11.0"
NPM_VERSION = "10.9.1"
YARN_VERSION = "3.2.4"
YARN_ENABLE_IMMUTABLE_INSTALLS = "false"

[build]
  command = "yarn install --immutable && gatsby build"

[functions]
  directory = "functions"

[[redirects]]
  from = "https://jillianserenity.dev/*"
  to = "https://jillian.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://lofibytes.dev/*"
  to = "https://jillian.dev/:splat"
  status = 301
  force = true
