[build.environment]
# NODE_OPTIONS = "--max_old_space_size=4096"
NODE_VERSION = "18.12.1"
NPM_VERSION = "9.1.1"

[[redirects]]
  from = "https://jillianserenity.dev/*"
  to = "https://jillian.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://lofibytes.dev/*"
  to = "https://jillian.dev/:splat"
  status = 301
  force = true
